### PR TITLE
feat(gui): basic chat app interface using streamlit

### LINKED ISSUE #18: feat(gui): create a simple graphical interface to interact with the system

### PR DESCRIPTION
**Pull request by mratanusarkar**
resolves #18

### CODE REVIEW

**Comment by mratanusarkar** [comment]
@soumik12345 could you check the following for me, and give some inputs:

- [ ] need toggle to dark/light mode in streamlit. light mode helps during a demo.
- [ ] since I don't have mistral API key, I couldn't test the running of the GUI
- [ ] need help with the "model selector" dropdown(s) in GUI, and what options should be there for all 3 cases
- [ ] to check if we deploy the app somewhere?
- [ ] feedback on the app GUI in its current state.

**Comment by soumik12345** [comment]
>  need toggle to dark/light mode in streamlit. light mode helps during a demo.

Although not officially by streamlit, there's a [hacky way](https://discuss.streamlit.io/t/changing-the-streamlit-theme-with-a-toggle-button-solution/56842) to solve it.

**Comment by mratanusarkar** [comment]
> Although not officially by streamlit, there's a [hacky way](https://discuss.streamlit.io/t/changing-the-streamlit-theme-with-a-toggle-button-solution/56842) to solve it.

went through this, and tried implementing it, but it reloads the entire app and is glitchy.
as of now, I have found this in the settings ([source](https://docs.streamlit.io/get-started/fundamentals/additional-features#themes)):

change_theme

**Review by mratanusarkar — COMMENTED** [review]
merging in the current working state

**Pull request merged**
